const PRODUCT_DATA = [
	{
		name: 'EUROLINE 810 ',
		productId: 'EURO19938201',
		brandName: 'EUROLINE',
		category: 'Pop Up Toasters',
		companyAssured: false,
		rating: '4.2',
		price: '12232',
		discount: '50%',
		imageURL:
			'https://rukminim1.flixcart.com/image/416/416/k5lcvbk0/pop-up-toaster/2/j/w/euroline-820-pop-up-810-pop-up-original-imafz8h3duveqgh7.jpeg?q=70',
		sellerName: 'telform inc.',
		isNewProduct: true,
	},
	{
		name: 'Morphy Richards ',
		productId: 'EURO19938202',
		brandName: 'Morphy',
		category: 'Microwave Ovens',
		companyAssured: true,
		rating: '3.9',
		price: '10999',
		discount: '11%',
		imageURL:
			'https://rukminim1.flixcart.com/image/416/416/microwave-new/v/q/y/morphy-richard-25cg-original-imaec2ddymudmze3.jpeg?q=70',
		sellerName: 'Kwitch Retails',
		isNewProduct: false,
	},
	{
		name: 'Red Beanie',
		productId: 'EURO19938203',
		brandName: 'Morphy',
		category: 'Microwave Ovens',
		companyAssured: true,
		rating: '3.9',
		price: '1856',
		discount: '11%',
		imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
		sellerName: 'Kwitch Retails',
		isNewProduct: false,
	},
	{
		name: 'Wolf Cap',
		productId: 'EURO19938204',
		brandName: 'Morphy',
		category: 'Microwave Ovens',
		companyAssured: true,
		rating: '3.9',
		price: '1400',
		discount: '11%',
		imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
		sellerName: 'Kwitch Retails',
		isNewProduct: false,
	},
	{
		name: 'Blue Snapback',
		productId: 'EURO19938205',
		brandName: 'Morphy',
		category: 'Microwave Ovens',
		companyAssured: true,
		rating: '3.9',
		price: '1600',
		discount: '11%',
		imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
		sellerName: 'Kwitch Retails',
		isNewProduct: false,
	},
	{
		name: 'Adidas NMD',
		productId: 'EURO19938206',
		brandName: 'Morphy',
		category: 'Microwave Ovens',
		companyAssured: true,
		rating: '3.9',
		price: '2200',
		discount: '11%',
		imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
		sellerName: 'Kwitch Retails',
		isNewProduct: false,
	},
	{
		name: 'Adidas Yeezy',
		productId: 'EURO19938207',
		brandName: 'Morphy',
		category: 'Microwave Ovens',
		companyAssured: true,
		rating: '3.9',
		price: '2800',
		discount: '11%',
		imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
		sellerName: 'Kwitch Retails',
		isNewProduct: false,
	},
	{
		name: 'Black Converse',
		productId: 'EURO19938208',
		brandName: 'Morphy',
		category: 'Microwave Ovens',
		companyAssured: true,
		rating: '3.9',
		price: '1100',
		discount: '11%',
		imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
		sellerName: 'Kwitch Retails',
		isNewProduct: false,
	},
	{
		name: 'Floral Dress',
		productId: 'EURO19938209',
		brandName: 'Morphy',
		category: 'Microwave Ovens',
		companyAssured: true,
		rating: '3.9',
		price: '8000',
		discount: '11%',
		imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
		sellerName: 'Kwitch Retails',
		isNewProduct: false,
	},
	{
		name: 'Red Dots Dress',
		productId: 'EURO19938210',
		brandName: 'Morphy',
		category: 'Microwave Ovens',
		companyAssured: true,
		rating: '3.9',
		price: '2700',
		discount: '11%',
		imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
		sellerName: 'Kwitch Retails',
		isNewProduct: false,
	},
	{
		name: 'Striped Sweater',
		productId: 'EURO19938211',
		brandName: 'Morphy',
		category: 'Microwave Ovens',
		companyAssured: true,
		rating: '3.9',
		price: '4500',
		discount: '11%',
		imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
		sellerName: 'Kwitch Retails',
		isNewProduct: false,
	},
	{
		name: 'Yellow Track Suit',
		productId: 'EURO19938212',
		brandName: 'Morphy',
		category: 'Microwave Ovens',
		companyAssured: true,
		rating: '3.9',
		price: '13500',
		discount: '11%',
		imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
		sellerName: 'Kwitch Retails',
		isNewProduct: false,
	},
];

export default PRODUCT_DATA;
